import { EventKinds, EventLevels, EventSources } from './types';

export const LEVEL_CONFIG = {
  [EventLevels.Info]: {
    bg: 'bg-slate-500',
    text: 'text-white',
    border: 'border-slate-400',
    label: '참고',
  },
  [EventLevels.Minor]: {
    bg: 'bg-blue-600',
    text: 'text-white',
    border: 'border-blue-400',
    label: '관심',
  },
  [EventLevels.Moderate]: {
    bg: 'bg-yellow-500',
    text: 'text-slate-900',
    border: 'border-yellow-300',
    label: '우려',
  },
  [EventLevels.Severe]: {
    bg: 'bg-orange-600',
    text: 'text-white',
    border: 'border-orange-400',
    label: '중대',
  },
  [EventLevels.Critical]: {
    bg: 'bg-red-700',
    text: 'text-white',
    border: 'border-red-500',
    label: '치명',
  },
};

export const EVENT_LEVEL_SOUNDS: Partial<Record<EventLevels, string>> = {
  [EventLevels.Moderate]: '/sounds/level-moderate.mp3',
  [EventLevels.Severe]: '/sounds/level-severe.mp3',
  [EventLevels.Critical]: '/sounds/level-critical.mp3',
};

export const EVENT_KIND_LABELS: Record<EventKinds, string> = {
  [EventKinds.Other]: '기타',
  [EventKinds.Quake]: '지진',
  [EventKinds.Ai]: 'AI',
  [EventKinds.Drought]: '가뭄',
  [EventKinds.Livestock]: '가축질병',
  [EventKinds.Wind]: '강풍',
  [EventKinds.Dry]: '건조',
  [EventKinds.Transport]: '교통',
  [EventKinds.TrafficCrash]: '교통사고',
  [EventKinds.TrafficCtrl]: '교통통제',
  [EventKinds.Finance]: '금융',
  [EventKinds.Snow]: '대설',
  [EventKinds.FineDust]: '미세먼지',
  [EventKinds.CivDef]: '민방공',
  [EventKinds.Collapse]: '붕괴',
  [EventKinds.Wildfire]: '산불',
  [EventKinds.Landslide]: '산사태',
  [EventKinds.Water]: '수도',
  [EventKinds.Fog]: '안개',
  [EventKinds.Energy]: '에너지',
  [EventKinds.Epidemic]: '전염병',
  [EventKinds.Blackout]: '정전',
  [EventKinds.Tsunami]: '지진해일',
  [EventKinds.Typhoon]: '태풍',
  [EventKinds.Terror]: '테러',
  [EventKinds.Telecom]: '통신',
  [EventKinds.Explosion]: '폭발',
  [EventKinds.Heat]: '폭염',
  [EventKinds.HighSeas]: '풍랑',
  [EventKinds.Cold]: '한파',
  [EventKinds.Rain]: '호우',
  [EventKinds.Flood]: '홍수',
  [EventKinds.Fire]: '화재',
  [EventKinds.Pollution]: '환경오염',
  [EventKinds.YellowDust]: '황사',
  [EventKinds.O3]: '오존',
  [EventKinds.CrowdDensity]: '인파밀집',
  [EventKinds.WildAnimal]: '야생동물',
  [EventKinds.Cyber]: '사이버',
  [EventKinds.SpaceWeather]: '우주환경',
};

export const EVENT_KIND_ICONS: Record<EventKinds, string> = {
  [EventKinds.Other]: '❔',
  [EventKinds.Quake]: '🎯',
  [EventKinds.Ai]: '🐦',
  [EventKinds.Drought]: '🏜️',
  [EventKinds.Livestock]: '🐮',
  [EventKinds.Wind]: '💨',
  [EventKinds.Dry]: '☀️',
  [EventKinds.Transport]: '🚦',
  [EventKinds.TrafficCrash]: '💥',
  [EventKinds.TrafficCtrl]: '🚧',
  [EventKinds.Finance]: '💹',
  [EventKinds.Snow]: '❄️',
  [EventKinds.FineDust]: '🌫️',
  [EventKinds.CivDef]: '🛡️',
  [EventKinds.Collapse]: '🏚️',
  [EventKinds.Wildfire]: '🌲',
  [EventKinds.Landslide]: '⛰️',
  [EventKinds.Water]: '🚰',
  [EventKinds.Fog]: '🌁',
  [EventKinds.Energy]: '⚡',
  [EventKinds.Epidemic]: '🦠',
  [EventKinds.Blackout]: '💡',
  [EventKinds.Tsunami]: '🌊',
  [EventKinds.Typhoon]: '🌀',
  [EventKinds.Terror]: '💣',
  [EventKinds.Telecom]: '📡',
  [EventKinds.Explosion]: '🧨',
  [EventKinds.Heat]: '🥵',
  [EventKinds.HighSeas]: '⛵',
  [EventKinds.Cold]: '🥶',
  [EventKinds.Rain]: '🌧️',
  [EventKinds.Flood]: '🌊',
  [EventKinds.Fire]: '🔥',
  [EventKinds.Pollution]: '🏭',
  [EventKinds.YellowDust]: '🟡',
  [EventKinds.O3]: '🧪',
  [EventKinds.CrowdDensity]: '👥',
  [EventKinds.WildAnimal]: '🐗',
  [EventKinds.Cyber]: '🌐',
  [EventKinds.SpaceWeather]: '🛰️',
};

export const getEventKindIcon = (kind: number): string => EVENT_KIND_ICONS[kind as EventKinds] ?? '?';

export const EVENT_KIND_VALUES: EventKinds[] = Object.values(EventKinds).filter(
  (value): value is EventKinds => typeof value === 'number',
);

export const STATUS_SOURCE_LABELS: Record<EventSources, string> = {
  [EventSources.SafekoreaSms]: '문자',
  [EventSources.MoisPressRelease]: '보도',
  [EventSources.MsitPressRelease]: '보도',
  [EventSources.KmaMicroEarthquake]: '미소지진',
  [EventSources.KmaPewsEarthquake]: '국내지진',
  [EventSources.KmaOverseasEarthquake]: '국외지진',
  [EventSources.NfdsFireDispatch]: '화재출동',
  [EventSources.KmaWeatherWarning]: '기상특보',
  [EventSources.KmaAwsObservation]: '기상관측',
  [EventSources.UticTrafficIncident]: '교통돌발',
  [EventSources.AirkoreaPmWarning]: 'PM',
  [EventSources.AirkoreaO3Warning]: 'O3',
  [EventSources.FloodAlert]: '홍수',
  [EventSources.ForestFireInfo]: '산불현황',
  [EventSources.ForestFireWarning]: '산불경보',
  [EventSources.LandslideForecast]: '산사태',
  [EventSources.NcscCyberCrisis]: '사이버',
  [EventSources.NctcTerrorAlert]: '테러',
  [EventSources.KpxPowerSupply]: '전력',
  [EventSources.YnaNews]: '뉴스',
  [EventSources.KasaSpaceWeatherWarning]: '우주환경',
  [EventSources.KasaSpaceWeatherCrisisAlert]: '전파경보',
};

export const EVENT_SOURCE_LABELS: Record<EventSources, string> = {
  [EventSources.SafekoreaSms]: '행안부',
  [EventSources.MoisPressRelease]: '행안부',
  [EventSources.MsitPressRelease]: '과기정통부',
  [EventSources.KmaMicroEarthquake]: '기상청',
  [EventSources.KmaPewsEarthquake]: '기상청',
  [EventSources.KmaOverseasEarthquake]: '기상청',
  [EventSources.NfdsFireDispatch]: '소방청',
  [EventSources.KmaWeatherWarning]: '기상청',
  [EventSources.KmaAwsObservation]: '기상청',
  [EventSources.UticTrafficIncident]: '경찰청',
  [EventSources.AirkoreaPmWarning]: '기후부',
  [EventSources.AirkoreaO3Warning]: '기후부',
  [EventSources.FloodAlert]: '기후부',
  [EventSources.ForestFireInfo]: '산림청',
  [EventSources.ForestFireWarning]: '산림청',
  [EventSources.LandslideForecast]: '산림청',
  [EventSources.NcscCyberCrisis]: '국정원',
  [EventSources.NctcTerrorAlert]: '국조실',
  [EventSources.KpxPowerSupply]: '산업부',
  [EventSources.YnaNews]: '연합뉴스',
  [EventSources.KasaSpaceWeatherWarning]: '우주청',
  [EventSources.KasaSpaceWeatherCrisisAlert]: '우주청',
};

export const EVENT_SOURCE_LINKS: Partial<Record<EventSources, string>> = {
  [EventSources.SafekoreaSms]: 'https://www.safekorea.go.kr/idsiSFK/neo/sfk/cs/sfc/dis/disasterMsgList.jsp?menuSeq=679',
  [EventSources.MoisPressRelease]:
    'https://www.mois.go.kr/frt/bbs/type010/commonSelectBoardList.do?bbsId=BBSMSTR_000000000008',
  [EventSources.MsitPressRelease]: 'https://www.msit.go.kr/bbs/list.do?sCode=user&mPid=208&mId=307',
  [EventSources.KmaMicroEarthquake]: 'https://www.weather.go.kr/w/earthquake-volcano/recent.do',
  [EventSources.KmaPewsEarthquake]: 'https://www.weather.go.kr/w/earthquake-volcano/recent.do',
  [EventSources.KmaOverseasEarthquake]: 'https://www.weather.go.kr/w/earthquake-volcano/recent.do',
  [EventSources.NfdsFireDispatch]: 'https://nfds.go.kr/dashboard/monitor.do',
  [EventSources.KmaWeatherWarning]: 'https://www.weather.go.kr/w/special-report/overall.do',
  [EventSources.KmaAwsObservation]: 'https://www.weather.go.kr/w/weather/land/aws-obs.do',
  [EventSources.UticTrafficIncident]: 'https://www.utic.go.kr/map/map.do?menu=incident',
  [EventSources.AirkoreaPmWarning]: 'https://www.airkorea.or.kr/web/pmWarning?pMENU_NO=115',
  [EventSources.AirkoreaO3Warning]: 'https://www.airkorea.or.kr/web/o3Warning?pMENU_NO=116',
  [EventSources.FloodAlert]: 'https://m.flood.go.kr/floodList.do',
  [EventSources.ForestFireInfo]: 'https://fd.forest.go.kr/ffas/pubConn/movePage/sub1.do',
  [EventSources.ForestFireWarning]: 'https://fd.forest.go.kr/ffas/index.jsp',
  [EventSources.LandslideForecast]: 'https://sansatai.forest.go.kr/',
  [EventSources.NcscCyberCrisis]: 'https://www.ncsc.go.kr/PageLink.do',
  [EventSources.NctcTerrorAlert]: 'http://www.nctc.go.kr/nctc/information/alertIssuanceStatus.do',
  [EventSources.KpxPowerSupply]: 'https://new.kpx.or.kr/',
  [EventSources.KasaSpaceWeatherWarning]: 'https://spaceweather.kasa.go.kr/Alarm.do',
  [EventSources.KasaSpaceWeatherCrisisAlert]: 'https://spaceweather.kasa.go.kr/Alarm.do',
  [EventSources.YnaNews]: 'https://www.yna.co.kr/',
};

export const getEventSourceLink = (sourceId: number): string | null =>
  EVENT_SOURCE_LINKS[sourceId as EventSources] ?? null;

export const SOURCE_DISPLAY_ORDER: EventSources[] = [
  EventSources.SafekoreaSms,
  EventSources.MoisPressRelease,
  EventSources.MsitPressRelease,
  EventSources.KmaMicroEarthquake,
  EventSources.KmaPewsEarthquake,
  EventSources.KmaOverseasEarthquake,
  EventSources.KmaWeatherWarning,
  EventSources.KmaAwsObservation,
  EventSources.NfdsFireDispatch,
  EventSources.UticTrafficIncident,
  EventSources.AirkoreaPmWarning,
  EventSources.AirkoreaO3Warning,
  EventSources.FloodAlert,
  EventSources.ForestFireInfo,
  EventSources.ForestFireWarning,
  EventSources.LandslideForecast,
  EventSources.NcscCyberCrisis,
  EventSources.NctcTerrorAlert,
  EventSources.KpxPowerSupply,
  EventSources.KasaSpaceWeatherWarning,
  EventSources.KasaSpaceWeatherCrisisAlert,
  EventSources.YnaNews,
];

export const CATEGORY_PAGE_SIZE = 6;
export const SIDEBAR_MIN_LEVEL = EventLevels.Moderate;
